name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP }}
          username: ${{ secrets.GCE_INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/indramhrt/HFG-Dashboard-Web
            git pull origin main
            docker compose up -d --build
